image_dir: sample_dataset/
job_dir: sample_jobdir/

dataprep:
  run: True
  samples_file: sample_configfile.json
  resize: True

train:
  run: True
  cloud: False

evaluate:
  run: True        # führt evaluation aus mit output auf stdout
  report:
    create: True    # jobxyz/report/report.ipynb report.pdf report.html
    kernel_name: any_kernel
    export_html: True # export as html
    export_pdf: False # export as pdf

cloud:
  cloud_tag: image_atm_example_tag
  provider: aws
  tf_dir: cloud/aws
  region: eu-west-1
  vpc_id: vpc-example
  instance_type: p2.xlarge
  bucket: s3://example-bucket
  destroy: True
